-- ==========================================================================
-- CODE MEETS AI COMPETITION DATABASE - SCHEMA STEP 4: DUO SCHEMA
-- File: /schema/duo_schema.sql
-- Description:
--   Creates the 'duos' table for Layer 3 and Layer 4 duo competition stages.
--   Two existing users are paired by admin into a duo team.
--   Scores are automatically derived from users.average_layer_1 +
--   users.average_layer_2 and kept in sync via triggers.
--
-- SCORING SCALE NOTES (inspected from existing schemas):
--   - users.average_layer_1 and users.average_layer_2 are on a RAW scale
--     (e.g. 0–100), NOT a 0–10 scale.
--   - users.total_score = average_layer_1 + average_layer_2 (max ~200 raw).
--   - combined_layer_1_average in duos is NORMALIZED to 0–10 as:
--       ((player_1_total_score + player_2_total_score) / 2) / 10
--     where player_total_score = users.average_layer_1 + users.average_layer_2
--   - layer_3_marks and layer_4_marks are already on a 0–10 scale (admin entry).
--   - total_marks = combined_layer_1_average + layer_3_marks + layer_4_marks
--     (max = 10 + 10 + 10 = 30)
--
-- Execution Order: Run AFTER user_schema.sql, layer1_schema.sql, layer2_schema.sql.
-- ==========================================================================

-- ==========================================================================
-- SECTION 1: TABLE CREATION
-- ==========================================================================

CREATE TABLE IF NOT EXISTS public.duos (

  -- -------------------------------------------------------------------------
  -- Primary Key: sequential duo registration number
  -- -------------------------------------------------------------------------
  serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- -------------------------------------------------------------------------
  -- Unique Duo Identifier (used for relationships and API lookups)
  -- -------------------------------------------------------------------------
  duo_id UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,

  -- -------------------------------------------------------------------------
  -- Player 1: references an existing user by UUID
  -- -------------------------------------------------------------------------
  player_1_id UUID NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  player_1_name TEXT,  -- Denormalized for display; synced via trigger

  -- -------------------------------------------------------------------------
  -- Player 2: references an existing user by UUID
  -- -------------------------------------------------------------------------
  player_2_id UUID NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  player_2_name TEXT,  -- Denormalized for display; synced via trigger

  -- -------------------------------------------------------------------------
  -- Validation: a player cannot be paired with themselves
  -- -------------------------------------------------------------------------
  CONSTRAINT chk_duo_different_players CHECK (player_1_id <> player_2_id),

  -- -------------------------------------------------------------------------
  -- Combined Layer 1+2 Average (Normalized to 0–10 scale)
  -- Formula:
  --   player_1_score = users.average_layer_1 + users.average_layer_2  (raw)
  --   player_2_score = users.average_layer_1 + users.average_layer_2  (raw)
  --   combined_layer_1_average = ((player_1_score + player_2_score) / 2) / 10
  -- Auto-calculated by trigger; admin CANNOT manually set this.
  -- -------------------------------------------------------------------------
  combined_layer_1_average NUMERIC DEFAULT 0.0
    CHECK (combined_layer_1_average >= 0.0 AND combined_layer_1_average <= 10.0),

  -- -------------------------------------------------------------------------
  -- Layer 3 & Layer 4 Marks (Admin-entered, 0–10 scale)
  -- May be NULL initially (not yet evaluated)
  -- -------------------------------------------------------------------------
  layer_3_marks NUMERIC
    CHECK (layer_3_marks IS NULL OR (layer_3_marks >= 0.0 AND layer_3_marks <= 10.0)),

  layer_4_marks NUMERIC
    CHECK (layer_4_marks IS NULL OR (layer_4_marks >= 0.0 AND layer_4_marks <= 10.0)),

  -- -------------------------------------------------------------------------
  -- Total Marks (Auto-calculated by trigger; admin CANNOT manually set this)
  -- Formula:
  --   total_marks = combined_layer_1_average
  --                 + COALESCE(layer_3_marks, 0)
  --                 + COALESCE(layer_4_marks, 0)
  -- Maximum possible: 10 + 10 + 10 = 30
  -- -------------------------------------------------------------------------
  total_marks NUMERIC DEFAULT 0.0
    CHECK (total_marks >= 0.0),

  -- -------------------------------------------------------------------------
  -- Timestamps
  -- -------------------------------------------------------------------------
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ==========================================================================
-- SECTION 2: DUPLICATE DUO PROTECTION
-- Prevent both (Player A, Player B) AND (Player B, Player A) from existing.
-- This is enforced by a unique constraint on the SORTED pair of UUIDs,
-- implemented via a unique index on LEAST/GREATEST expressions.
-- ==========================================================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_duos_unique_pair
  ON public.duos (LEAST(player_1_id, player_2_id), GREATEST(player_1_id, player_2_id));

-- ==========================================================================
-- SECTION 3: STANDARD INDEXES
-- ==========================================================================

CREATE INDEX IF NOT EXISTS idx_duos_duo_id        ON public.duos(duo_id);
CREATE INDEX IF NOT EXISTS idx_duos_player_1_id   ON public.duos(player_1_id);
CREATE INDEX IF NOT EXISTS idx_duos_player_2_id   ON public.duos(player_2_id);
CREATE INDEX IF NOT EXISTS idx_duos_total_marks    ON public.duos(total_marks DESC);

-- ==========================================================================
-- SECTION 4: updated_at AUTO-REFRESH TRIGGER
-- Reuses the shared function created in user_schema.sql
-- ==========================================================================

DROP TRIGGER IF EXISTS trigger_duos_updated_at ON public.duos;
CREATE TRIGGER trigger_duos_updated_at
  BEFORE UPDATE ON public.duos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- ==========================================================================
-- SECTION 5: TRIGGER FUNCTION — SYNC PLAYER NAMES FROM users TABLE
-- Ensures player_1_name and player_2_name always match users.name.
-- Prevents accidental mismatch between player_id and player_name on INSERT
-- or UPDATE of player_1_id / player_2_id.
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.sync_duo_player_names()
RETURNS TRIGGER AS $$
DECLARE
  v_player_1_name TEXT;
  v_player_2_name TEXT;
BEGIN
  -- Look up authoritative names from users table
  SELECT name INTO v_player_1_name
    FROM public.users
   WHERE user_id = NEW.player_1_id;

  SELECT name INTO v_player_2_name
    FROM public.users
   WHERE user_id = NEW.player_2_id;

  -- Enforce name consistency regardless of what was submitted
  NEW.player_1_name = v_player_1_name;
  NEW.player_2_name = v_player_2_name;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_sync_duo_player_names ON public.duos;
CREATE TRIGGER trigger_sync_duo_player_names
  BEFORE INSERT OR UPDATE OF player_1_id, player_2_id ON public.duos
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_duo_player_names();

-- ==========================================================================
-- SECTION 6: TRIGGER FUNCTION — CALCULATE combined_layer_1_average
-- Reads CURRENT users.total_score (= average_layer_1 + average_layer_2)
-- for both players, computes the duo average, and normalizes to 0–10 scale.
-- Also cascades to recalculate total_marks.
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.calculate_duo_combined_average()
RETURNS TRIGGER AS $$
DECLARE
  v_p1_total NUMERIC;
  v_p2_total NUMERIC;
  v_combined  NUMERIC;
BEGIN
  -- Fetch each player's raw total score (average_layer_1 + average_layer_2)
  SELECT COALESCE(total_score, 0.0) INTO v_p1_total
    FROM public.users
   WHERE user_id = NEW.player_1_id;

  SELECT COALESCE(total_score, 0.0) INTO v_p2_total
    FROM public.users
   WHERE user_id = NEW.player_2_id;

  -- Normalize the duo average to 0–10 scale
  -- Raw scores are on ~0–200 range (average_layer_1 + average_layer_2 each 0–100)
  -- Duo combined: ((p1_total + p2_total) / 2) / 10
  v_combined := ((v_p1_total + v_p2_total) / 2.0) / 10.0;

  -- Clamp to [0.0, 10.0] as a safety net
  v_combined := GREATEST(0.0, LEAST(10.0, v_combined));

  NEW.combined_layer_1_average := ROUND(v_combined, 2);

  -- Immediately cascade: recalculate total_marks using latest marks
  NEW.total_marks :=
    ROUND(
      NEW.combined_layer_1_average
      + COALESCE(NEW.layer_3_marks, 0.0)
      + COALESCE(NEW.layer_4_marks, 0.0),
    2);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_calculate_duo_combined_average ON public.duos;
CREATE TRIGGER trigger_calculate_duo_combined_average
  BEFORE INSERT OR UPDATE OF player_1_id, player_2_id ON public.duos
  FOR EACH ROW
  EXECUTE FUNCTION public.calculate_duo_combined_average();

-- ==========================================================================
-- SECTION 7: TRIGGER FUNCTION — RECALCULATE total_marks
-- Fires when admin updates layer_3_marks or layer_4_marks.
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.recalculate_duo_total_marks()
RETURNS TRIGGER AS $$
BEGIN
  NEW.total_marks :=
    ROUND(
      COALESCE(NEW.combined_layer_1_average, 0.0)
      + COALESCE(NEW.layer_3_marks, 0.0)
      + COALESCE(NEW.layer_4_marks, 0.0),
    2);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_recalculate_duo_total_marks ON public.duos;
CREATE TRIGGER trigger_recalculate_duo_total_marks
  BEFORE INSERT OR UPDATE OF layer_3_marks, layer_4_marks, combined_layer_1_average
  ON public.duos
  FOR EACH ROW
  EXECUTE FUNCTION public.recalculate_duo_total_marks();

-- ==========================================================================
-- SECTION 8: TRIGGER FUNCTION — PROPAGATE users SCORE CHANGES TO duos
-- When a user's average_layer_1 or average_layer_2 changes (via layer_1 or
-- layer_2 sync triggers), their duo record must be updated too.
-- This trigger fires on the users table AFTER score updates and refreshes
-- combined_layer_1_average + total_marks for all duos involving that user.
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.propagate_user_score_to_duos()
RETURNS TRIGGER AS $$
DECLARE
  duo_row RECORD;
  v_p1_total NUMERIC;
  v_p2_total NUMERIC;
  v_combined  NUMERIC;
BEGIN
  -- Only propagate when scores actually changed
  IF (OLD.average_layer_1 IS NOT DISTINCT FROM NEW.average_layer_1)
     AND (OLD.average_layer_2 IS NOT DISTINCT FROM NEW.average_layer_2) THEN
    RETURN NEW;
  END IF;

  -- Loop over every duo that involves this user (as either player)
  FOR duo_row IN
    SELECT duo_id, player_1_id, player_2_id, layer_3_marks, layer_4_marks
      FROM public.duos
     WHERE player_1_id = NEW.user_id OR player_2_id = NEW.user_id
  LOOP
    -- Get both players' current total_score
    SELECT COALESCE(total_score, 0.0) INTO v_p1_total
      FROM public.users WHERE user_id = duo_row.player_1_id;

    SELECT COALESCE(total_score, 0.0) INTO v_p2_total
      FROM public.users WHERE user_id = duo_row.player_2_id;

    -- Normalize to 0–10
    v_combined := GREATEST(0.0, LEAST(10.0, ((v_p1_total + v_p2_total) / 2.0) / 10.0));

    UPDATE public.duos
       SET combined_layer_1_average = ROUND(v_combined, 2),
           total_marks = ROUND(
             v_combined
             + COALESCE(duo_row.layer_3_marks, 0.0)
             + COALESCE(duo_row.layer_4_marks, 0.0),
           2),
           updated_at = NOW()
     WHERE duo_id = duo_row.duo_id;
  END LOOP;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_propagate_user_score_to_duos ON public.users;
CREATE TRIGGER trigger_propagate_user_score_to_duos
  AFTER UPDATE OF total_score ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.propagate_user_score_to_duos();

-- ==========================================================================
-- SECTION 9: ROW LEVEL SECURITY (RLS)
-- ==========================================================================

ALTER TABLE public.duos ENABLE ROW LEVEL SECURITY;

-- Policy 1: Anyone can read duo records (for leaderboard)
CREATE POLICY "Public Duos Read Access"
  ON public.duos
  FOR SELECT
  USING (true);

-- Policy 2: Admin can create duo pairings
CREATE POLICY "Public Duos Insert Access"
  ON public.duos
  FOR INSERT
  WITH CHECK (true);

-- Policy 3: Admin can update duo records & marks
CREATE POLICY "Public Duos Update Access"
  ON public.duos
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Policy 4: Admin can delete duo records
CREATE POLICY "Public Duos Delete Access"
  ON public.duos
  FOR DELETE
  USING (true);

-- ==========================================================================
-- SECTION 10: REFERENCE QUERIES (comments only — not DDL)
-- ==========================================================================

-- Example: Create a duo (admin backend via service_role)
-- INSERT INTO public.duos (player_1_id, player_2_id)
-- VALUES ('uuid-of-player-1', 'uuid-of-player-2');
-- All other fields (names, combined_layer_1_average, total_marks) are
-- auto-populated by triggers.

-- Example: Admin updates Layer 3 marks
-- UPDATE public.duos
--    SET layer_3_marks = 7.5
--  WHERE duo_id = 'uuid-of-duo';
-- total_marks is recalculated automatically by trigger.

-- Example: Full duo leaderboard ordered by total_marks
-- SELECT
--   d.serial_number,
--   d.player_1_name,
--   d.player_2_name,
--   d.combined_layer_1_average,
--   d.layer_3_marks,
--   d.layer_4_marks,
--   d.total_marks
-- FROM public.duos d
-- ORDER BY d.total_marks DESC;

-- Example: View a specific user's duo(s)
-- SELECT *
-- FROM public.duos
-- WHERE player_1_id = 'uuid-here' OR player_2_id = 'uuid-here';

-- ==========================================================================
-- END OF duo_schema.sql
-- ==========================================================================
